name: Run eslint and prettier before merging to main

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: yarn install
      - run: yarn eslint .
      - run: yarn prettier
